/**
 * Generates a Google Calendar event link for election deadlines.
 * @param title - The name of the election event/deadline
 * @param dateStr - The ISO date string for the event
 * @param details - Brief description of the event
 * @returns A formatted Google Calendar URL
 */
export const generateGoogleCalendarLink = (title: string, dateStr: string, details: string): string => {
  const date = new Date(dateStr);
  const start = date.toISOString().replace(/-|:|\.\d\d\d/g, '');
  
  // Election events usually last the full day or have a specific window; 
  // setting a 2-hour reminder window by default.
  const endDate = new Date(date.getTime() + 2 * 60 * 60 * 1000);
  const end = endDate.toISOString().replace(/-|:|\.\d\d\d/g, '');

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: `[CivicPulse] ${title}`,
    dates: `${start}/${end}`,
    details: `${details}\n\nGenerated by CivicPulse Election Navigator.`,
    location: 'Your Local Polling Station',
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
};
